const problemTopics = [
  { value: 'array', label: 'Array' },
  { value: 'string', label: 'String' },
  { value: 'hashTable', label: 'Hash table' },
  { value: 'linkedList', label: 'Linked list' },
  { value: 'stack', label: 'Stack' },
  { value: 'queue', label: 'Queue' },
  { value: 'tree', label: 'Tree' },
  { value: 'binaryTree', label: 'Binary tree' },
  { value: 'binarySearchTree', label: 'Binary search tree' },
  { value: 'heap', label: 'Heap / priority queue' },
  { value: 'graph', label: 'Graph' },
  { value: 'dfs', label: 'DFS' },
  { value: 'bfs', label: 'BFS' },
  { value: 'topologicalSort', label: 'Topological sort' },
  { value: 'unionFind', label: 'Union find' },
  { value: 'trie', label: 'Trie' },
  { value: 'dp', label: 'Dynamic programming' },
  { value: 'greedy', label: 'Greedy' },
  { value: 'backtracking', label: 'Backtracking' },
  { value: 'binarySearch', label: 'Binary search' },
  { value: 'twoPointers', label: 'Two pointers' },
  { value: 'slidingWindow', label: 'Sliding window' },
  { value: 'sorting', label: 'Sorting' },
  { value: 'recursion', label: 'Recursion' },
  { value: 'divideAndConquer', label: 'Divide and conquer' },
  { value: 'bitManipulation', label: 'Bit manipulation' },
  { value: 'math', label: 'Math' },
  { value: 'numberTheory', label: 'Number theory' },
  { value: 'prefixSum', label: 'Prefix sum' },
  { value: 'matrix', label: 'Matrix' },
  { value: 'intervals', label: 'Intervals' },
  { value: 'monotonicStack', label: 'Monotonic stack' },
  { value: 'shortestPath', label: 'Shortest path' },
  { value: 'segmentTree', label: 'Segment tree' },
  { value: 'fenwickTree', label: 'Fenwick tree' },
  { value: 'geometry', label: 'Geometry' },
  { value: 'design', label: 'Design' },
];

const problemTags = problemTopics.map((topic) => topic.value);

module.exports = {
  problemTopics,
  problemTags,
};
